name: Say hello

on:
  push:
    branches:
      - practice-ci

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Andres!"
      - name: Dime la fecha
        run: date
      - run: ls -l